### ISSUE TITLE
Please add readme.md with demo link

### ISSUE THREAD

**Issue by Lupusa87** [EdCharbeneau/BlazeDown#2]
After additional search I found [live demo](http://edcharbeneau.com/BlazeDown/)
I have seen it long time ago and remembered that this sample was live.

Please add link to readme.md for another people to see live demo and not to think it not exists.

Also I wonder why your project is not in community's [samples list](https://blazor.net/community.html)

Best Regards

**Comment by EdCharbeneau** [comment]
Thanks for the reminder. I'll get on this shortly.
